UPDATE t_table SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 1;
UPDATE t_table1 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 2;
UPDATE t_table4 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 5;
UPDATE t_table5 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 6;
UPDATE t_table1 SET _boolean = true, _long = null, _decimal = null, _double = null, _float = null, _string = 'Update', _byte = null, _date = now(), _time = now(), _timestamp = now() WHERE _int = 1;
UPDATE t_table6 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 7;
UPDATE t_table6 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 5;
UPDATE t_table7 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 6;
UPDATE t_table8 SET _boolean = true, _long = 0, _decimal = 0, _double = 0, _float = 0, _string = 'Update', _byte = 0, _date = now(), _time = now(), _timestamp = now() WHERE _int = 1;
